# Use this workflow to initialize your repository with the fimware you need for your keyboard
# if you have multiple keyboards, you need to have 1 copy of this file per keyboard
# rename the name below so that you can see the different keyboards in your github actions
name: ergosteel

# You will need to manually trigger this workflow
on:  ['workflow_dispatch']

jobs:
  initialize-firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      max-parallel: 1  
      matrix:
        # Replace the following with the keyboard you want to setup.  
        # Only 1 keyboard is supported.  For more keyboards, copy and rename this file.
        keyboard: ['ergodox_steel']
        # Keymap of the keyboard to setup.  Multiple keymaps can be setup following this example: ['default','jpconstantineau']
        keymap: ['default']
        # keyboard configuration. Multiple configs can be setup following this example: ['left','right']
        keyboard_config: ['left','right']
        # hardware configuration. must have both components of the path in the BlueMicro_BLE keyboard examples path
        hardware_config: ['feathernrf52840']
        # Available options
        # feather52832 - use this for most nRF52832 based boards (needs Arduino_nRF52_Bootloader)
        # bluemicro_nrf52840
        # bluemacro_nrf52840
        # nice_nano
        # pca10056 - use this for all other nRF52840 based boards not listed above (needs Arduino_nRF52_Bootloader)
        compile_with: ['bluemicro_nrf52840']

    # you shouldn't need to edit anything below
    steps:
      - name: checkout builder repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
      - name: update from last run
        run: git pull
      - name: setup conditions
        id: job_conditions
        run: |
          if [ -d ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }} ]; then
          echo "::set-output name=firmware-here::true"
          else
          echo "::set-output name=firmware-here::false"
          fi
      - name: clone BlueMicro_BLE repository
        run: |
          git clone https://github.com/photomattmills/BlueMicro_BLE.git
      - name: setup job variables
        id: job_variables
        run: |
          echo "::set-output name=firmware-name::${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}"
          echo "::set-output name=hardware-config::$(find BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/hardware/ -name hardware_config.h | grep ${{ matrix.hardware_config }} )"
      - name: copy main firmware files
        run: |
          cp BlueMicro_BLE/firmware/*.cpp ${{ steps.job_variables.outputs.firmware-name }}
          cp BlueMicro_BLE/firmware/*.h ${{ steps.job_variables.outputs.firmware-name }}
          cp BlueMicro_BLE/firmware/firmware.ino ${{ steps.job_variables.outputs.firmware-name }}/${{ steps.job_variables.outputs.firmware-name }}.ino
      - name: copy board specific files
        run: |
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/config/${{ matrix.keyboard_config }}/keyboard_config.h ${{ steps.job_variables.outputs.firmware-name }}
          cp ${{ steps.job_variables.outputs.hardware-config }} ${{ steps.job_variables.outputs.firmware-name }}
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.h ${{ steps.job_variables.outputs.firmware-name }}
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.cpp ${{ steps.job_variables.outputs.firmware-name }} 
      - name: remove BlueMicro_BLE repository
        run: |
          rm -r BlueMicro_BLE
      - name: check back in the changes to this repo
        run: |
          ls -l
          git config --global user.name 'gh-actions'
          git config --global user.email 'gh-actions@noreply.github.com'
          git add ${{ steps.job_variables.outputs.firmware-name }}
          git commit -m "Initialized ${{ steps.job_variables.outputs.firmware-name }} using GitHub Actions"
          git push
    
